---
# Example CI/CD workflow for Docker applications
# Projects: mail_box_indexer, wildduck
#
# Copy this file to your project's .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write      # For creating GitHub releases
  id-token: write      # For NPM provenance
  deployments: write   # For deployment tracking

jobs:
  cicd:
    uses: johnqh/workflows/.github/workflows/unified-cicd.yml@main
    with:
      project-type: "docker-app"
      docker-image-name: "mail_box_indexer"  # Change to your Docker image name
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
