---
# Example CI/CD workflow for PUBLIC library projects
# Projects: design_system
#
# Automatically publishes to NPM when NPM_TOKEN is configured
# Copy this file to your project's .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write      # For creating GitHub releases
  id-token: write      # For NPM provenance
  deployments: write   # For deployment tracking

jobs:
  cicd:
    uses: johnqh/workflows/.github/workflows/unified-cicd.yml@main
    with:
      npm-access: "public"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
