---
# Example CI/CD workflow for web applications with Cloudflare Pages deployment
# Projects: mail_box
#
# Copy this file to your project's .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write      # For creating GitHub releases
  id-token: write      # For NPM provenance
  deployments: write   # For deployment tracking

jobs:
  cicd:
    uses: johnqh/workflows/.github/workflows/unified-cicd.yml@main
    with:
      project-type: "webapp"
      cloudflare-project-name: "0xmail-box"  # Change to your Cloudflare project name
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      VITE_REVENUECAT_API_KEY: ${{ secrets.VITE_REVENUECAT_API_KEY }}
      VITE_WILDDUCK_API_TOKEN: ${{ secrets.VITE_WILDDUCK_API_TOKEN }}
