---
# Example CI/CD workflow for web applications with Cloudflare Pages deployment
# Projects: mail_box
#
# Automatically deploys to Cloudflare Pages when CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID are configured
# Automatically deploys to Docker Hub when DOCKERHUB_USERNAME and DOCKERHUB_TOKEN are configured
# Copy this file to your project's .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write      # For creating GitHub releases
  id-token: write      # For NPM provenance
  deployments: write   # For deployment tracking

jobs:
  cicd:
    uses: johnqh/workflows/.github/workflows/unified-cicd.yml@main
    with:
      cloudflare-project-name: "0xmail-box"  # Change to your Cloudflare project name
      docker-image-name: "mail-box"  # Only used if Docker Hub secrets are configured
    secrets: inherit  # Pass all repository secrets to the workflow
